os: osx
language: csharp
mono: 6.4.0

# Only watch the development branch and tagged release.
branches:
 only:
   - /^osx-launcher-.*$/
   - master

# Compile only the main binary on default pushes
script:
 - make launcher

# Compile dependencies and build the launcher.zip before deploying
before_deploy:
 - make all

deploy:
  provider: releases
  api_key: ${GH_DEPLOY_API_KEY}
  file:
    - build/launcher.zip
    - build/libSDL2.dylib
    - build/liblua.5.1.dylib
    - build/libfreetype.6.dylib
    - build/libopenal.1.dylib
  skip_cleanup: true
  on:
    tags: true

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
